name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: # Build every day at 5PM UTC
    - cron: '0 17 * * *'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, macos-12, macos-13, macos-14 ]
        rust: [stable, beta, 1.74.1] # Minimum Rust Version Supported = 1.74.1
        experimental: [false]
        include:
          - os: ubuntu-latest
            rust: nightly
            experimental: true
          - os: macos-11
            rust: nightly
            experimental: true
          - os: macos-12
            rust: nightly
            experimental: true
          - os: macos-13
            rust: nightly
            experimental: true
          - os: macos-14
            rust: nightly
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: clippy

    - name: Run clippy (installed toolchain version as per matrix)
      run: |
        cargo clippy --all --tests --no-deps --all-targets --all-features -- --warn clippy::pedantic -D warnings
        rustc --version

    - name: ConfigureCoverage
      if: matrix.rust == 'nightly'
      run: |
        cargo install grcov
        rustup component add llvm-tools-preview
        echo RUSTFLAGS="-C instrument-coverage" >> "$GITHUB_ENV"
        echo LLVM_PROFILE_FILE="libproc-%p-%m.profraw" >> "$GITHUB_ENV"

    - name: Run Tests on Linux
      if: runner.os == 'Linux'
      run: env "PATH=$PATH" cargo test

    - name: Run Tests as Root on Mac
      if: runner.os == 'macOS'
      run: sudo env "PATH=$PATH" cargo test

    - name: UploadCoverage
      if: matrix.rust == 'stable'
      run: make upload-coverage